name: Compilar Ejecutable Windows (Manual)

on:
  workflow_dispatch: # Permite ejecutar el proceso manualmente con un botón

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Descargar codigo del repositorio
      uses: actions/checkout@v4

    - name: Configurar entorno Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'pip'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Garantizar carpeta de recursos (Evita fallos en PyInstaller)
      shell: pwsh
      run: |
        if (!(Test-Path -Path "assets")) {
            New-Item -ItemType Directory -Path "assets"
        }

    - name: Compilar aplicacion con PyInstaller
      run: |
        pyinstaller build.spec

    - name: Empaquetar ejecutable en archivo ZIP
      shell: pwsh
      run: |
        if (Test-Path -Path "dist/TheGaragePOS.exe") {
            Compress-Archive -Path dist/TheGaragePOS.exe -DestinationPath dist/TheGaragePOS_Windows.zip -Force
        } else {
            Write-Error "No se encontro el archivo dist/TheGaragePOS.exe tras la compilacion."
            exit 1
        }

    - name: Guardar ejecutable como artefacto descargable
      uses: actions/upload-artifact@v4
      with:
        name: TheGaragePOS-Instalador
        path: dist/TheGaragePOS_Windows.zip
        retention-days: 14
